### ISSUE TITLE
deploy stack can't auto create network

### ISSUE THREAD

**Issue by 502647092** [cuigh/swirl#29]
![image](https://user-images.githubusercontent.com/10203793/56939196-a5c57580-6b39-11e9-94a5-66570958480a.png)

```
version: "3"

services:
  theia:
    image: miaowoo/theia:next
    ports:
      - 8008:3000
    environment:
      GOPROXY: https://goproxy.io
    volumes:
      - theia:/home/project
volumes:
  theia:
    driver_opts:
      type: nfs4
      o: addr=192.168.2.219,rw
      device: ":/home/app/nfs/docker/theia"
```
