### ISSUE TITLE
invalid mount config for type "bind": bind source path does not exist: /data/swirl

### ISSUE THREAD

**Issue by nexovec** [cuigh/swirl#52]
Hello,

I am doing a swarm deployment of Swirl. My `swirl` tasks get rejected with this message: `invalid mount config for type "bind": bind source path does not exist: /data/swirl` using the following `compose.yml`.
```yaml
version: '3.3'
services:
  manager_agent:
    image: cuigh/socat:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      mode: global
      placement:
        constraints:
         - node.role == manager
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    ports:
     - 7081:8081
    networks:
     - default
    logging:
      driver: json-file
  mongodb:
    image: mongo:latest
    networks:
     - default
    logging:
      driver: json-file
  swirl:
    image: cuigh/swirl:latest
    environment:
      AGENTS: swirl_manager_agent,swirl_worker_agent
      DB_ADDRESS: mongodb://mongodb:27017/swirl
      DB_TYPE: mongo
      DOCKER_ENDPOINT: tcp://swirl_manager_agent:2375
    ports:
     - 8001:8001
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == worker
  worker_agent:
    image: cuigh/socat:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      mode: global
      placement:
        constraints:
         - node.role == worker
networks:
  default:
    driver: overlay
```
I also noticed there are no clear instructions on how to supply database credentials, am I going to be prompted for those in the UI once I get it running?

Thank you very much.

**Comment by cuigh** [comment]
> I also noticed there are no clear instructions on how to supply database credentials, am I going to be prompted for those in the UI once I get it running?
> 
You can configure database authentication information through the connection string of the database: 
https://www.mongodb.com/docs/manual/reference/connection-string/

For example: mongodb://{user}:{password}@mongodb:27017/swirl?authSource=admin

**Comment by nexovec** [comment]
Will do, do you have some insight into what the mount config error is? I'm not binding anything like that in this compose  yaml.

**Comment by cuigh** [comment]
It's weird. This error looks like DB_ TYPE option is set to bolt, which means Swirl did not read the environment variables you set in composite.yml file.

**Comment by nexovec** [comment]
I tried to set the database to bolt just to get something working first. I'm getting `panic: failed to load storage engine: failed to open bolt database: open /data/swirl/swirl.db: no such file or directory`. Again, here is the `compose.yml`:
```
version: '3.8'

services:
  swirl:
    image: cuigh/swirl
    environment:
      DB_TYPE: bolt
      DB_ADDRESS: /data/swirl
      # DB_ADDRESS: mongodb://root:example@mongo:27017/swirl?authSource=admin
      DOCKER_ENDPOINT: tcp://swirl_manager_agent:2375
      AGENTS: swirl_manager_agent,swirl_worker_agent
    networks:
      - net
    depends_on:
      - mongo
    ports:
      - "8001:8001"
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

  manager_agent:
    image: cuigh/socat
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints: [ node.role == manager ]

  worker_agent:
    image: cuigh/socat
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints: [ node.role == manager ]

networks:
  host:
    external: true
  net:
```
I would be happy to try to create it manually and bind it into the docker container, but I don't know the file name, you'd have to tell me the correct `bolt.Open` call.

I will be happy to do a pull request with compose files that work out-of-the-box for both supported databases, provided that I get them to work.
